version: "3.8"
services:
  frontend:
    image: arturgrigoryan1/front:ed3c84c92e4021248db25e53e438b8c6b7e887de
    
#    depends_on:
#      - backend
    ports:
      - "3000:3000"
    networks:
      - network-backend
#  backend:
 #   image: arturgrigoryan1/back
  #  depends_on:
   #   - mongo
 #   ports:
 #     - "3001:3001"
  #  networks: 
   #  - network-backend
  
#  mongo:
#    image: mongo
#    restart: always
#    volumes: 
#      - mongodb_data:/data/db
#    environment: 
#      MONGODB_INITDB_ROOT_USERNAME: username
#      MONGODB_INITDB_ROOT_PASSWORD: password
    # uncomment following lines to access db locally
    # ports:
    #   - 27017:27017
#    networks: 
#     - network-backend

networks:
  network-backend:

#volumes: 
#  mongodb_data:
ngodb_data:
