version: "3.8"
services:
  frontend:
    image: arturgrigoryan1/front:01a387c
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - network-backend
  backend:
    image: arturgrigoryan1/back:fa78cec
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    networks: 
     - network-backend
  
  mongo:
    image: mongo
#    env_file: docker.env
    restart: always
    volumes: 
      - mongodb_data:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: admin
      MONGODB_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: todos
    ports:
      - 27017:27017
    networks: 
      - network-backend

networks:
  network-backend:

volumes: 
  mongodb_data:
