version: "3.8"
services:
  frontend:
    image: arturgrigoryan1/front:57380aa
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - network-backend
  backend:    
    image: arturgrigoryan1/back:e7be42a
    container_name: backend
    restart: always
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    networks: 
      - network-backend
  
  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongodb_data:/data/db
#    environment: 
#      MONGODB_INITDB_ROOT_USERNAME: ${MONGO_USER}
#      MONGODB_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
#      MONGO_INITDB_DATABASE: ${MONGO_DB}
    env_file: 
      - docker.env
    ports:
      - "27017:27017"
    networks: 
      - network-backend

networks:
  network-backend:

volumes: 
  mongodb_data:
