version: "3.8"
services:
  frontend:
    image: arturgrigoryan1/front:3119507
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - network-backend
  backend:    
    image: arturgrigoryan1/back:84170b4
    container_name: backend
    restart: always
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    networks: 
      - network-backend
  
  mongo:
    image: mongo
    env_file: docker.env
    restart: always
    volumes: 
      - mongodb_data:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "27017:27017"
    networks: 
      - network-backend

networks:
  network-backend:

volumes: 
  mongodb_data:
